version: "3"
services:
    web:
        depends_on:
            - mysql
        image: rosudavidg/survket-backend:latest
        deploy:
            replicas: 4
            resources:
                limits:
                    cpus: "0.2"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "8888:5000"
        networks:
            - webnet
    mysql:
        restart: always
        image: rosudavidg/survket-database:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'mypassword'
            MYSQL_DATABASE: "survket_db"
            MYSQL_USER: 'test'
            MYSQL_PASS: 'pass'
        volumes:
            - my-datavolume:/var/lib/mysql
        ports:
            - "6603:3306"
        networks:
            - webnet
volumes:
    my-datavolume:
networks:
    webnet:

