version: "3"
services:
  backend:
    image: rosudavidg/survket-backend:latest
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - webnet
networks:
  webnet: