version: "3"
services:
    web:
        # depends_on:
        #     - mysql
        image: back
        deploy:
            replicas: 4
            resources:
                limits:
                    cpus: "0.2"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "8888:5000"
        environment:
            - DATABASE_HOST=mysql
        networks:
            - webnet
    mysql:
        restart: always
        image: data
        environment:
            MYSQL_ROOT_PASSWORD: 'supersecret'
            MYSQL_DATABASE: "survket_db"
            MYSQL_USER: 'test'
            MYSQL_PASS: 'pass'
        volumes:
            - my-datavolume:/var/lib/mysql
        ports:
            - "33070:3306"
        expose:
            - "3306"
        networks:
            - webnet
volumes:
    my-datavolume:
networks:
    webnet:
        # driver: bridge
