version: "3"
services:
  backend:
    # image: rosudavidg/survket-backend
    image: survket_backend
    depends_on:
      - database
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8888:5000"
    environment:
      - DATABASE_USER=postgres
      - DATABASE_HOST=database
      - DATABASE_NAME=survket_db
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=5432
      - JWT_ISSUER=survket_backend
      - JWT_SUBJECT=Authentication token
      - JWT_AUDIENCE=survket_frontend
      - JWT_EXPIRESIN=1w
      - JWT_SECRET_KEY=myawesomeultrasecretkey
    networks:
      - webnet
    volumes:
      - ./backend/:/usr/src/app
  database:
    # image: rosudavidg/survket-database
    image: survket_database
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: survket_db
    volumes:
      - survket_database_volume:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - webnet
  email:
    # image: rosudavidg/survket-email:latest
    image: survket_email
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    expose:
      - "5000"
    networks:
      - webnet
volumes:
  survket_database_volume:
networks:
  webnet:
